
name: "JS Actions"

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"
      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "Learning Lab User"
